### ISSUE TITLE
hi ^^

### ISSUE THREAD

**Issue by dewster** [BrandenSoropia/LoLTeams#3]
Hi :)
i all time get this error: 
`Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
    at C:\Users\Dewster\Desktop\lolteam\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:98:20
    at Connection.<anonymous> (C:\Users\Dewster\node_modules\pg\lib\client.js:185:5)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (C:\Users\Dewster\node_modules\pg\lib\connection.js:71:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

idea or solutions? 
ty answer mate

**Comment by BrandenSoropia** [comment]
Ah sorry for the trouble, I should have written instructions on setup/how to run it!

You need to host a Postgres database on port 5432 then the error should be resolved. If you dont have Postgres and use mac, I use this one: [http://postgresapp.com/](url) that should work right away.

If you run into anything else, feel free to ask! Otherwise hope this helps!
